### ISSUE TITLE
Hive TRV Support

### ISSUE THREAD

**Issue by MagicalTrev89** [Rendili/hive-for-home-assistant#3]
Just got some hive TRVs and found they do not show in home assistant.

Have been looking at it and will raise a PR soon.

**Comment by gemignani** [comment]
Hi, any updates on this? If you could share the patch about how far did you get.

**Comment by MagicalTrev89** [comment]
@gemignani The main changes for this have been merged into the pihiveapi, next step is to get it into HA. Had some issues with my Pi this last week so bit delayed getting the latest PR raised.

**Comment by xdmate** [comment]
How hard would it be to transfer this plugin over to a standard home bridge platform?  I'm running HOOBs &  I'm dying for Hive support, but all of the plugins are outdated or only work with Britsh gas.

**Comment by xdmate** [comment]
@MagicalTrev89 How hard would it be to add support for the Hive Heating & Cooling thermostat?

**Comment by MagicalTrev89** [comment]
@xdmate I don't have one of them to develop against, Does the one you have work at all and just missing the cooling or does it not appear in HA ?

In theory it shouldn't be too hard to add it, i suspect if it doesn't appear at all it will be a separate device type on the API which is currently being ignored or not requested.

**Comment by KJonline** [comment]
@xdmate is your thermostat the US version? If it is this has been mentioned by other people and it’s currently being investigated to be developed on.

**Comment by xdmate** [comment]
> @xdmate is your thermostat the US version? If it is this has been mentioned by other people and it’s currently being investigated to be developed on.

I posted here and opened an issue of my own, I wasn't sure if I'd get a reply. @Rendili replied to me earlier, but, yeah it is the US version. :)

**Comment by KJonline** [comment]
This should be in home assistant versio 100 or 101

**Comment by KJonline** [comment]
@MagicalTrev89 it looks like HA version 101 has been deployed with your TRV support changes.
