### ISSUE TITLE
Hive TRV battery status

### ISSUE THREAD

**Issue by yakox** [Rendili/hive-for-home-assistant#7]
Hi - I have added some Hive TRVs to my existing Hive system and they showed up in Home  Assistant (0.101.3) without any problems.

There is a battery status indication for the TRVs in the Hive mobile app but I can't find this info in Home Assistant. Assuming the battery information is available from Hive, would it be possible to expose it in Home Assistant? It would be great to be able to set up a HA notification for low TRV battery levels.

**Comment by 230delphi** [comment]
install the custom components - they include a battery indicator.
sensor.\<device name\>_thermostat_battery_level

https://github.com/Rendili/hive-for-home-assistant/tree/master/custom_components/hive

**Comment by yakox** [comment]
Apologies, I should have mentioned that I already have the custom components installed and up to date using HACS. The only battery sensor I see is for the main thermostat unit.

**Comment by xenocryst1** [comment]
Is there a resolution to this?  I also don't see the battery levels for the TRVs. Thanks.

**Comment by KJonline** [comment]
Currently this feature is not being looked into as TRV,s was implemented by someone else  and not the maintainers of this repo. We are currently looking for someone to extract their hive data for us so we can maintain TRV’s.

**Comment by xenocryst1** [comment]
I'm happy to help with some anonymised data if you let me know what you need and how to obtain it?

**Comment by KJonline** [comment]
Hi @xenocryst1 Sorry for a late reply. Do you have a Home Assistant community account I can message you on privately the instruction on how to do it?

**Comment by xenocryst1** [comment]
Hi @KJonline, I'm on the Home Assistant community as xenocryst.

**Comment by KJonline** [comment]
Hi @xenocryst1, I have sent you a private message on home assistant forum explaining  how to get the hive data

**Comment by sym0nd0** [comment]
I'm also happy to provide data, if needed. Same username.

**Comment by KJonline** [comment]
@sym0nd0 thanks do the offer, I got some data to look at and use. A question I have though is does the TRV have the ability to boost it?

**Comment by sym0nd0** [comment]
No worries. Yeah, you can manually boost an individual TRV, for a minimum of 30 minutes and definable up to 32°C. Not sure if it needs to be factored in, but there's also Heat on Demand (HoD) and if its enabled it will boost the local 'stat to a defined temperature and keep boosting it until the TRV is up to the target temp. 
![Screenshot_20200712-105925_Hive](https://user-images.githubusercontent.com/55590428/87243644-83163880-c42f-11ea-9424-d5ef74e0ccf9.jpg)
![Screenshot_20200712-105948_Hive](https://user-images.githubusercontent.com/55590428/87243645-83aecf00-c42f-11ea-894b-972120e11e97.jpg)

**Comment by B-Hartley** [comment]
Hi,
Is there any progress with getting TRV battery status added into the custom component? or the core component?
I can provide info on how the battery levels are given by the API if it helps?

Thanks
