### ISSUE TITLE
Latest HA version

### ISSUE THREAD

**Issue by PSJMcNeill** [Rendili/hive-for-home-assistant#8]
Is this still working with latest HA?
Tried adding it via HACS as custom repo no joy.

Added it manually to custom components but can't see it in HA after restart

**Comment by leopold005** [comment]
I'm having a similar issue.  Just upgraded HASSIO to v0.110 and I can see the update for this in HACS, but the upgrade button does nothing.  Not a massive issue right now, but if you can find a fix for it, that would be brilliant.

**Comment by GuruPG** [comment]
I’m also getting an error in HACS. 
As follows:
An Error Occurred While Processing

GitHub returned 404 for https://api.github.com/repos/Rendili/hive-for-home-assistant/git/trees/v2019.1

**Comment by KJonline** [comment]
Hi all, the 2019 release has been removed there are upcoming changes to the pyhive infuatructure plus and upgrade to the home assistant component.  I’m not sure why hacs is still replicating this version as it’s been removed.

**Comment by GuruPG** [comment]
@KJonline Many thanks for the information. 
Your work is much appreciated.

**Comment by leopold005** [comment]
> Hi all, the 2019 release has been removed there are upcoming changes to the pyhive infuatructure plus and upgrade to the home assistant component. I’m not sure why hacs is still replicating this version as it’s been removed.

Ah, that would explain it! Thanks for the update, I’ll stop trying to install it.
